/*
 * Copyright 2010-2020 JetBrains s.r.o. and Kotlin Programming Language contributors.
 * Use of this source code is governed by the Apache 2.0 license that can be found in the license/LICENSE.txt file.
 */

package org.jetbrains.kotlin.idea.util

import com.intellij.openapi.diagnostic.Logger
import com.intellij.openapi.progress.ProcessCanceledException
import com.intellij.openapi.progress.ProgressManager
import com.intellij.openapi.project.DumbService
import com.intellij.openapi.project.Project
import com.intellij.openapi.util.Computable
import com.intellij.openapi.util.ThrowableComputable
import org.jetbrains.annotations.Nls
import org.jetbrains.kotlin.idea.util.application.runReadAction
import java.util.concurrent.Future
import java.util.concurrent.TimeUnit
import java.util.concurrent.TimeoutException

object ProgressIndicatorUtils {
    private val LOG = Logger.getInstance(ProgressIndicatorUtils::class.java)

    @JvmStatic
    fun <T> underModalProgress(
        project: Project,
        @Nls progressTitle: String,
        computable: Computable<T>
    ): T {
        val dumbService = DumbService.getInstance(project)
        val useAlternativeResolve = dumbService.isAlternativeResolveEnabled
        val inReadAction =
            ThrowableComputable<T, RuntimeException> { runReadAction { return@runReadAction computable.compute() } }
        val process =
            if (useAlternativeResolve) ThrowableComputable { dumbService.computeWithAlternativeResolveEnabled(inReadAction) } else inReadAction
        return ProgressManager.getInstance().runProcessWithProgressSynchronously(process, progressTitle, true, project)
    }

    @JvmStatic
    fun <T> awaitWithCheckCanceled(future: Future<T>): T {
        while (true) {
            ProgressManager.checkCanceled()
            try {
                return future.get(50, TimeUnit.MILLISECONDS)
            } catch (e: TimeoutException) {
                // ignore
            } catch (e: Exception) {
                LOG.warn(e)
                throw ProcessCanceledException(e)
            }
        }
    }

}